Chapter7_4 파트 추가
Robot-Vision-LAB/hands-on-linux pull request #28
Opened 2023-02-08 12:24 UTC by hololee

- 파트 추가

2023-02-08 12:31 UTC, jstar0525 requested changes
파일 확장자 형식 수정

2023-02-08 12:31 UTC, jstar0525 commented on chapter07/18. 셸에서 조건 판정하기/README,md
> +# 셸에서 조건 판정하기
README,md를 README.md로 수정해줘

2023-02-08 12:40 UTC, jstar0525 approved these changes
👍

2023-02-19 12:16 UTC, jeongahyun approved these changes
굿굿

2023-02-26 11:35 UTC, RoBoTics-JHJ approved these changes

2023-02-26 11:42 UTC, merged